Fix/presence teams
equinor/fusion-components pull request #896
Opened 2020-12-16 10:58 UTC by ingridklepsvik

2021-01-26 08:05 UTC, olerichard requested changes

2021-01-26 08:05 UTC, olerichard commented on src/components/people/PersonPhoto/PersonPresenceIcon/index.tsx
> +        if (presenceAvailability === 'Available' || 'AvailableIdle') {
This probably dosnt work as it should, same issue on line 35
Needs to be similar to how it is on line 32

2021-01-26 12:16 UTC, olerichard approved these changes

2021-02-02 09:05 UTC, odinr approved these changes

2021-02-02 09:20 UTC, merged